### ISSUE TITLE
If there is chain A already, rename chains will not work

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/rna-pdb-tools#63]
```
[mm] rp21$ git:(master) ✗ rna_pdb_toolsx.py --inplace --rpr 21_solution_2_rpr.pdb
  0% (0 of 1) |                                                                                          | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "/home/magnus/work-src/rna-pdb-tools/bin/rna_pdb_toolsx.py", line 283, in <module>
    verbose=args.verbose)
  File "/Users/magnus/work-src/rna-pdb-tools/rna_pdb_tools/rna_pdb_tools_lib.py", line 954, in get_rnapuzzle_ready
    chain.id = new_chains.pop(0)
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/site-packages/Bio/PDB/Entity.py", line 92, in id
    " this entity.".format(self._id, value, value))
ValueError: Cannot change id from `A` to `A`. The id `A` is already used for a sibling of this entity.
[mm] rp21$ git:(master) ✗ rna_pdb_toolsx.py --inplace --rpr --dont_rename_chains 21_solution_2_rpr.pdb
  0% (0 of 1) |                                                                                          | Elapsed Time: 0:00:00 ETA:  --:--:--
````

**Comment by mmagnus** [comment]
also in test.sh 

```
./rna_pdb_toolsx.py --no_hr --rpr input/A_YG_A.pdb --renumber_residues > output/A_YG_A_renumbered.pdb
Traceback (most recent call last):
  File "./rna_pdb_toolsx.py", line 283, in <module>
    verbose=args.verbose)
  File "/Users/magnus/work-src/rna-pdb-tools/rna_pdb_tools/rna_pdb_tools_lib.py", line 954, in get_rnapuzzle_ready
    chain.id = new_chains.pop(0)
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/site-packages/Bio/PDB/Entity.py", line 92, in id
    " this entity.".format(self._id, value, value))
ValueError: Cannot change id from `A` to `A`. The id `A` is already used for a sibling of this entity.
./rna_pdb_toolsx.py --no_hr --rpr input/A_YG_A.pdb > output/A_YG_A_norenumbered.pdb
Traceback (most recent call last):
  File "./rna_pdb_toolsx.py", line 283, in <module>
    verbose=args.verbose)
  File "/Users/magnus/work-src/rna-pdb-tools/rna_pdb_tools/rna_pdb_tools_lib.py", line 954, in get_rnapuzzle_ready
    chain.id = new_chains.pop(0)
  File "/home/magnus/work/opt/miniconda2/lib/python2.7/site-packages/Bio/PDB/Entity.py", line 92, in id
    " this entity.".format(self._id, value, value))
ValueError: Cannot change id from `A` to `A`. The id `A` is already used for a sibling of this entity.

```
