### ISSUE TITLE
Unable to parse a stockholm format file using rna-pdb-tools, but can do so using biopython

### ISSUE THREAD

**Issue by thedjofsis** [mmagnus/rna-pdb-tools#66]
[IE2.gissd.sto.txt](https://github.com/mmagnus/rna-pdb-tools/files/2296880/IE2.gissd.sto.txt)

I'm able to parse this file using SeqIO module in Biopython but not by RNAalignment from rna-pdb-tools. I need this because of some other functionalities in RNAalignment that I'd like to use. Please check and let me know if there is a bug here or the problem is with formatting of the file.

The error that I get is:
`Traceback (most recent call last):
  File "map_consensus_remove_gaps.py", line 27, in <module>
    test = ra.RNAalignment('alignment_files/' + file_name)
  File "/usr/local/lib/python2.7/dist-packages/rna_pdb_tools/utils/rna_alignment/rna_alignment.py", line 419, in __init__
    seq_id, seq_seq = seq.split()
ValueError: need more than 0 values to unpack`

**Comment by thedjofsis** [comment]
Alright, I'll update my rna-pdb-tools and inform you.
